// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBzUpFh1k0xYGDw4se5KcNNIXmCZvagFg',
    appId: '1:942309874852:web:3a303ccbefc14706fbda31',
    messagingSenderId: '942309874852',
    projectId: 'chatapp-d2a9f',
    authDomain: 'chatapp-d2a9f.firebaseapp.com',
    storageBucket: 'chatapp-d2a9f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmxf1YXpdIwUk_9LH19_PgDidtReMX0yY',
    appId: '1:942309874852:android:67d115387984a623fbda31',
    messagingSenderId: '942309874852',
    projectId: 'chatapp-d2a9f',
    storageBucket: 'chatapp-d2a9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs570wRiegv5vgXne6KA9wEL6wG1BH7HI',
    appId: '1:942309874852:ios:633a64c79fd8b7e7fbda31',
    messagingSenderId: '942309874852',
    projectId: 'chatapp-d2a9f',
    storageBucket: 'chatapp-d2a9f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs570wRiegv5vgXne6KA9wEL6wG1BH7HI',
    appId: '1:942309874852:ios:633a64c79fd8b7e7fbda31',
    messagingSenderId: '942309874852',
    projectId: 'chatapp-d2a9f',
    storageBucket: 'chatapp-d2a9f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBzUpFh1k0xYGDw4se5KcNNIXmCZvagFg',
    appId: '1:942309874852:web:fa004605f08b76cffbda31',
    messagingSenderId: '942309874852',
    projectId: 'chatapp-d2a9f',
    authDomain: 'chatapp-d2a9f.firebaseapp.com',
    storageBucket: 'chatapp-d2a9f.appspot.com',
  );
}
